const should = require("chai").should()
const Crispr = require("../crispr")
const fs = require("fs")

const schema_path = "./schemaorg/data/releases/9.0/schemaorg-all-http.jsonld"
const schema_contents = fs.readFileSync(schema_path, "utf-8")
const SCHEMA = JSON.parse(schema_contents)

let debug = false

before(() => {
  this.crispr = new Crispr(SCHEMA["@graph"], "http://schema.org/")
  if (debug) this.jay = {}
})

after(() => {
  if (debug) fs.writeFileSync(`./expected.json`, JSON.stringify(this.jay))
})

for (let [model, tests] of Object.entries({
  Thing: {
    "0": {
      fields: {
        potentialAction: { type: "Text" },
        identifier: { type: "Text" },
        sameAs: { type: "URL" },
        url: { type: "URL" },
        image: { type: "URL" },
        alternateName: { type: "Text" },
        name: { type: "Text" },
        description: { type: "Text" },
        mainEntityOfPage: { type: "URL" },
        disambiguatingDescription: { type: "Text" },
        subjectOf: { type: "Text" },
        additionalType: { type: "URL" },
      },
      name: "Thing",
      subs: [],
    },
    "1": {
      fields: {
        potentialAction: { type: "Action" },
        identifier: { type: "PropertyValue" },
        sameAs: { type: "URL" },
        url: { type: "URL" },
        image: { type: "ImageObject" },
        alternateName: { type: "Text" },
        name: { type: "Text" },
        description: { type: "Text" },
        mainEntityOfPage: { type: "CreativeWork" },
        disambiguatingDescription: { type: "Text" },
        subjectOf: { type: "CreativeWork" },
        additionalType: { type: "URL" },
      },
      name: "Thing",
      subs: [],
    },
  },
  Action: {
    "0": {
      fields: {
        instrument: { type: "Thing" },
        endTime: { type: "Time" },
        participant: { type: "Text" },
        result: { type: "Thing" },
        startTime: { type: "Time" },
        actionStatus: { type: "Text" },
        target: { type: "Text" },
        agent: { type: "Text" },
        error: { type: "Thing" },
        location: { type: "Text" },
        object: { type: "Thing" },
      },
      name: "Action",
      subs: ["Thing"],
    },
    "1": {
      fields: {
        instrument: { type: "Thing" },
        endTime: { type: "Time" },
        participant: { type: "Person" },
        result: { type: "Thing" },
        startTime: { type: "Time" },
        actionStatus: {
          type: "Text",
          enums: [
            "FailedActionStatus",
            "CompletedActionStatus",
            "ActiveActionStatus",
            "PotentialActionStatus",
          ],
        },
        target: { type: "EntryPoint" },
        agent: { type: "Person" },
        error: { type: "Thing" },
        location: { type: "PostalAddress" },
        object: { type: "Thing" },
      },
      name: "Action",
      subs: ["Thing"],
    },
  },
  CreativeWork: {
    "0": {
      fields: {
        typicalAgeRange: { type: "Text" },
        hasPart: { type: "CreativeWork" },
        sdDatePublished: { type: "Date" },
        educationalLevel: { type: "Text" },
        releasedEvent: { type: "Text" },
        schemaVersion: { type: "Text" },
        contentLocation: { type: "Text" },
        locationCreated: { type: "Text" },
        aggregateRating: { type: "Text" },
        temporalCoverage: { type: "Text" },
        accessModeSufficient: { type: "Text" },
        accountablePerson: { type: "Text" },
        mainEntity: { type: "Thing" },
        sdPublisher: { type: "Text" },
        spatialCoverage: { type: "Text" },
        reviews: { type: "Text" },
        exampleOfWork: { type: "CreativeWork" },
        maintainer: { type: "Text" },
        editor: { type: "Text" },
        offers: { type: "Text" },
        discussionUrl: { type: "URL" },
        award: { type: "Text" },
        sdLicense: { type: "CreativeWork" },
        copyrightHolder: { type: "Text" },
        accessibilityHazard: { type: "Text" },
        copyrightYear: { type: "Number" },
        awards: { type: "Text" },
        publisherImprint: { type: "Text" },
        commentCount: { type: "Text" },
        spatial: { type: "Text" },
        recordedAt: { type: "Text" },
        abstract: { type: "Text" },
        fileFormat: { type: "Text" },
        isPartOf: { type: "CreativeWork" },
        temporal: { type: "Text" },
        accessibilitySummary: { type: "Text" },
        inLanguage: { type: "Text" },
        educationalAlignment: { type: "Text" },
        associatedMedia: { type: "Text" },
        funder: { type: "Text" },
        position: { type: "Text" },
        audio: { type: "Text" },
        workExample: { type: "CreativeWork" },
        encoding: { type: "Text" },
        interactivityType: { type: "Text" },
        provider: { type: "Text" },
        character: { type: "Text" },
        sourceOrganization: { type: "Text" },
        audience: { type: "Text" },
        materialExtent: { type: "Text" },
        video: { type: "Text" },
        accessibilityFeature: { type: "Text" },
        publisher: { type: "Text" },
        text: { type: "Text" },
        publication: { type: "Text" },
        contributor: { type: "Text" },
        encodingFormat: { type: "Text" },
        review: { type: "Text" },
        accessibilityControl: { type: "Text" },
        license: { type: "CreativeWork" },
        sponsor: { type: "Text" },
        encodings: { type: "Text" },
        about: { type: "Thing" },
        isBasedOn: { type: "CreativeWork" },
        creator: { type: "Text" },
        publishingPrinciples: { type: "CreativeWork" },
        producer: { type: "Text" },
        correction: { type: "Text" },
        workTranslation: { type: "CreativeWork" },
        mentions: { type: "Thing" },
        contentReferenceTime: { type: "DateTime" },
        dateCreated: { type: "Date" },
        educationalUse: { type: "Text" },
        teaches: { type: "Text" },
        alternativeHeadline: { type: "Text" },
        datePublished: { type: "Date" },
        isAccessibleForFree: { type: "Boolean" },
        headline: { type: "Text" },
        translationOfWork: { type: "CreativeWork" },
        acquireLicensePage: { type: "CreativeWork" },
        conditionsOfAccess: { type: "Text" },
        citation: { type: "CreativeWork" },
        accessibilityAPI: { type: "Text" },
        interactionStatistic: { type: "Text" },
        contentRating: { type: "Text" },
        accessMode: { type: "Text" },
        material: { type: "Text" },
        isFamilyFriendly: { type: "Boolean" },
        assesses: { type: "Text" },
        keywords: { type: "Text" },
        version: { type: "Text" },
        dateModified: { type: "Date" },
        learningResourceType: { type: "Text" },
        genre: { type: "Text" },
        creativeWorkStatus: { type: "Text" },
        pattern: { type: "Text" },
        editEIDR: { type: "Text" },
        author: { type: "Text" },
        size: { type: "Text" },
        translator: { type: "Text" },
        timeRequired: { type: "Text" },
        usageInfo: { type: "CreativeWork" },
        isBasedOnUrl: { type: "CreativeWork" },
        thumbnailUrl: { type: "URL" },
        expires: { type: "Date" },
        comment: { type: "Text" },
      },
      name: "CreativeWork",
      subs: ["Thing"],
    },
    "1": {
      fields: {
        typicalAgeRange: { type: "Text" },
        hasPart: { type: "CreativeWork" },
        sdDatePublished: { type: "Date" },
        educationalLevel: { type: "DefinedTerm" },
        releasedEvent: { type: "PublicationEvent" },
        schemaVersion: { type: "Text" },
        contentLocation: { type: "Place" },
        locationCreated: { type: "Place" },
        aggregateRating: { type: "AggregateRating" },
        temporalCoverage: { type: "Text" },
        accessModeSufficient: { type: "ItemList" },
        accountablePerson: { type: "Person" },
        mainEntity: { type: "Thing" },
        sdPublisher: { type: "Person" },
        spatialCoverage: { type: "Place" },
        reviews: { type: "Review" },
        exampleOfWork: { type: "CreativeWork" },
        maintainer: { type: "Person" },
        editor: { type: "Person" },
        offers: { type: "Offer" },
        discussionUrl: { type: "URL" },
        award: { type: "Text" },
        sdLicense: { type: "CreativeWork" },
        copyrightHolder: { type: "Person" },
        accessibilityHazard: { type: "Text" },
        copyrightYear: { type: "Number" },
        awards: { type: "Text" },
        publisherImprint: { type: "Organization" },
        commentCount: { type: "Integer" },
        spatial: { type: "Place" },
        recordedAt: { type: "Event" },
        abstract: { type: "Text" },
        fileFormat: { type: "Text" },
        isPartOf: { type: "CreativeWork" },
        temporal: { type: "Text" },
        accessibilitySummary: { type: "Text" },
        inLanguage: { type: "Language" },
        educationalAlignment: { type: "AlignmentObject" },
        associatedMedia: { type: "MediaObject" },
        funder: { type: "Person" },
        position: { type: "Integer" },
        audio: { type: "AudioObject" },
        workExample: { type: "CreativeWork" },
        encoding: { type: "MediaObject" },
        interactivityType: { type: "Text" },
        provider: { type: "Person" },
        character: { type: "Person" },
        sourceOrganization: { type: "Organization" },
        audience: { type: "Text", enums: ["Researcher"] },
        materialExtent: { type: "QuantitativeValue" },
        video: { type: "Clip" },
        accessibilityFeature: { type: "Text" },
        publisher: { type: "Person" },
        text: { type: "Text" },
        publication: { type: "PublicationEvent" },
        contributor: { type: "Person" },
        encodingFormat: { type: "Text" },
        review: { type: "Review" },
        accessibilityControl: { type: "Text" },
        license: { type: "CreativeWork" },
        sponsor: { type: "Person" },
        encodings: { type: "MediaObject" },
        about: { type: "Thing" },
        isBasedOn: { type: "CreativeWork" },
        creator: { type: "Person" },
        publishingPrinciples: { type: "CreativeWork" },
        producer: { type: "Person" },
        correction: { type: "CorrectionComment" },
        workTranslation: { type: "CreativeWork" },
        mentions: { type: "Thing" },
        contentReferenceTime: { type: "DateTime" },
        dateCreated: { type: "Date" },
        educationalUse: { type: "Text" },
        teaches: { type: "DefinedTerm" },
        alternativeHeadline: { type: "Text" },
        datePublished: { type: "Date" },
        isAccessibleForFree: { type: "Boolean" },
        headline: { type: "Text" },
        translationOfWork: { type: "CreativeWork" },
        acquireLicensePage: { type: "CreativeWork" },
        conditionsOfAccess: { type: "Text" },
        citation: { type: "CreativeWork" },
        accessibilityAPI: { type: "Text" },
        interactionStatistic: { type: "InteractionCounter" },
        contentRating: { type: "Rating" },
        accessMode: { type: "Text" },
        material: { type: "Product" },
        isFamilyFriendly: { type: "Boolean" },
        assesses: { type: "DefinedTerm" },
        keywords: { type: "Text" },
        version: { type: "Text" },
        dateModified: { type: "Date" },
        learningResourceType: { type: "Text" },
        genre: { type: "Text" },
        creativeWorkStatus: { type: "DefinedTerm" },
        pattern: { type: "DefinedTerm" },
        editEIDR: { type: "Text" },
        author: { type: "Person" },
        size: { type: "DefinedTerm" },
        translator: { type: "Person" },
        timeRequired: { type: "Duration" },
        usageInfo: { type: "CreativeWork" },
        isBasedOnUrl: { type: "CreativeWork" },
        thumbnailUrl: { type: "URL" },
        expires: { type: "Date" },
        comment: { type: "Comment" },
      },
      name: "CreativeWork",
      subs: ["Thing"],
    },
  },
  Event: {
    "0": {
      fields: {
        maximumAttendeeCapacity: { type: "Text" },
        typicalAgeRange: { type: "Text" },
        organizer: { type: "Text" },
        attendees: { type: "Text" },
        aggregateRating: { type: "Text" },
        subEvents: { type: "Event" },
        offers: { type: "Text" },
        workFeatured: { type: "Text" },
        inLanguage: { type: "Text" },
        funder: { type: "Text" },
        remainingAttendeeCapacity: { type: "Text" },
        maximumPhysicalAttendeeCapacity: { type: "Text" },
        audience: { type: "Text" },
        actor: { type: "Text" },
        performers: { type: "Text" },
        endDate: { type: "Date" },
        eventSchedule: { type: "Text" },
        doorTime: { type: "Time" },
        contributor: { type: "Text" },
        review: { type: "Text" },
        sponsor: { type: "Text" },
        about: { type: "Thing" },
        subEvent: { type: "Event" },
        location: { type: "Text" },
        recordedIn: { type: "Text" },
        composer: { type: "Text" },
        isAccessibleForFree: { type: "Boolean" },
        performer: { type: "Text" },
        attendee: { type: "Text" },
        workPerformed: { type: "Text" },
        eventStatus: { type: "Text" },
        director: { type: "Text" },
        duration: { type: "Text" },
        maximumVirtualAttendeeCapacity: { type: "Text" },
        translator: { type: "Text" },
        eventAttendanceMode: { type: "Text" },
        startDate: { type: "Date" },
        superEvent: { type: "Event" },
        previousStartDate: { type: "Date" },
      },
      name: "Event",
      subs: ["Thing"],
    },
    "1": {
      fields: {
        maximumAttendeeCapacity: { type: "Integer" },
        typicalAgeRange: { type: "Text" },
        organizer: { type: "Organization" },
        attendees: { type: "Organization" },
        aggregateRating: { type: "AggregateRating" },
        subEvents: { type: "Event" },
        offers: { type: "Offer" },
        workFeatured: { type: "CreativeWork" },
        inLanguage: { type: "Language" },
        funder: { type: "Organization" },
        remainingAttendeeCapacity: { type: "Integer" },
        maximumPhysicalAttendeeCapacity: { type: "Integer" },
        audience: { type: "Text", enums: ["Researcher"] },
        actor: { type: "Person" },
        performers: { type: "Organization" },
        endDate: { type: "Date" },
        eventSchedule: { type: "Schedule" },
        doorTime: { type: "Time" },
        contributor: { type: "Organization" },
        review: { type: "Review" },
        sponsor: { type: "Organization" },
        about: { type: "Thing" },
        subEvent: { type: "Event" },
        location: { type: "PostalAddress" },
        recordedIn: { type: "CreativeWork" },
        composer: { type: "Organization" },
        isAccessibleForFree: { type: "Boolean" },
        performer: { type: "Organization" },
        attendee: { type: "Organization" },
        workPerformed: { type: "CreativeWork" },
        eventStatus: {
          type: "Text",
          enums: [
            "EventPostponed",
            "EventMovedOnline",
            "EventRescheduled",
            "EventScheduled",
            "EventCancelled",
          ],
        },
        director: { type: "Person" },
        duration: { type: "Duration" },
        maximumVirtualAttendeeCapacity: { type: "Integer" },
        translator: { type: "Organization" },
        eventAttendanceMode: {
          type: "Text",
          enums: [
            "OnlineEventAttendanceMode",
            "MixedEventAttendanceMode",
            "OfflineEventAttendanceMode",
          ],
        },
        startDate: { type: "Date" },
        superEvent: { type: "Event" },
        previousStartDate: { type: "Date" },
      },
      name: "Event",
      subs: ["Thing"],
    },
  },
  MedicalEntity: {
    "0": {
      fields: {
        medicineSystem: { type: "Text" },
        guideline: { type: "Text" },
        relevantSpecialty: { type: "Text" },
        legalStatus: { type: "Text" },
        recognizingAuthority: { type: "Text" },
        code: { type: "Text" },
        study: { type: "Text" },
      },
      name: "MedicalEntity",
      subs: ["Thing"],
    },
    "1": {
      fields: {
        medicineSystem: {
          type: "Text",
          enums: [
            "TraditionalChinese",
            "Homeopathic",
            "Osteopathic",
            "WesternConventional",
            "Ayurvedic",
            "Chiropractic",
          ],
        },
        guideline: { type: "MedicalGuideline" },
        relevantSpecialty: {
          type: "Text",
          enums: [
            "PrimaryCare",
            "SpeechPathology",
            "Genetic",
            "Rheumatologic",
            "Anesthesia",
            "Emergency",
            "Gynecologic",
            "Surgical",
            "Dentistry",
            "Nursing",
            "Hematologic",
            "Pulmonary",
            "Neurologic",
            "PharmacySpecialty",
            "PublicHealth",
            "Geriatric",
            "Podiatric",
            "Urologic",
            "Midwifery",
            "Musculoskeletal",
            "Dermatology",
            "DietNutrition",
            "Physiotherapy",
            "RespiratoryTherapy",
            "Psychiatric",
            "CommunityHealth",
            "Cardiovascular",
            "Toxicologic",
            "Gastroenterologic",
            "Oncologic",
            "Renal",
            "Dermatologic",
            "PlasticSurgery",
            "LaboratoryScience",
            "Obstetric",
            "Otolaryngologic",
            "Endocrine",
            "Pathology",
            "Infectious",
            "Optometric",
            "Pediatric",
            "Radiography",
          ],
        },
        legalStatus: { type: "DrugLegalStatus" },
        recognizingAuthority: { type: "Organization" },
        code: { type: "MedicalCode" },
        study: { type: "MedicalStudy" },
      },
      name: "MedicalEntity",
      subs: ["Thing"],
    },
    "2": {
      fields: {
        medicineSystem: {
          type: "Text",
          enums: [
            "TraditionalChinese",
            "Homeopathic",
            "Osteopathic",
            "WesternConventional",
            "Ayurvedic",
            "Chiropractic",
          ],
        },
        guideline: { type: "MedicalGuideline" },
        relevantSpecialty: {
          type: "Text",
          enums: [
            "PrimaryCare",
            "SpeechPathology",
            "Genetic",
            "Rheumatologic",
            "Anesthesia",
            "Emergency",
            "Gynecologic",
            "Surgical",
            "Dentistry",
            "Nursing",
            "Hematologic",
            "Pulmonary",
            "Neurologic",
            "PharmacySpecialty",
            "PublicHealth",
            "Geriatric",
            "Podiatric",
            "Urologic",
            "Midwifery",
            "Musculoskeletal",
            "Dermatology",
            "DietNutrition",
            "Physiotherapy",
            "RespiratoryTherapy",
            "Psychiatric",
            "CommunityHealth",
            "Cardiovascular",
            "Toxicologic",
            "Gastroenterologic",
            "Oncologic",
            "Renal",
            "Dermatologic",
            "PlasticSurgery",
            "LaboratoryScience",
            "Obstetric",
            "Otolaryngologic",
            "Endocrine",
            "Pathology",
            "Infectious",
            "Optometric",
            "Pediatric",
            "Radiography",
          ],
        },
        legalStatus: { type: "DrugLegalStatus" },
        recognizingAuthority: { type: "Organization" },
        code: { type: "MedicalCode" },
        study: { type: "MedicalStudy" },
      },
      name: "MedicalEntity",
      subs: ["Thing"],
    },
    "3": {
      fields: {
        medicineSystem: {
          type: "Text",
          enums: [
            "TraditionalChinese",
            "Homeopathic",
            "Osteopathic",
            "WesternConventional",
            "Ayurvedic",
            "Chiropractic",
          ],
        },
        guideline: { type: "MedicalGuideline" },
        relevantSpecialty: {
          type: "Text",
          enums: [
            "PrimaryCare",
            "SpeechPathology",
            "Genetic",
            "Rheumatologic",
            "Anesthesia",
            "Emergency",
            "Gynecologic",
            "Surgical",
            "Dentistry",
            "Nursing",
            "Hematologic",
            "Pulmonary",
            "Neurologic",
            "PharmacySpecialty",
            "PublicHealth",
            "Geriatric",
            "Podiatric",
            "Urologic",
            "Midwifery",
            "Musculoskeletal",
            "Dermatology",
            "DietNutrition",
            "Physiotherapy",
            "RespiratoryTherapy",
            "Psychiatric",
            "CommunityHealth",
            "Cardiovascular",
            "Toxicologic",
            "Gastroenterologic",
            "Oncologic",
            "Renal",
            "Dermatologic",
            "PlasticSurgery",
            "LaboratoryScience",
            "Obstetric",
            "Otolaryngologic",
            "Endocrine",
            "Pathology",
            "Infectious",
            "Optometric",
            "Pediatric",
            "Radiography",
          ],
        },
        legalStatus: { type: "DrugLegalStatus" },
        recognizingAuthority: { type: "Organization" },
        code: { type: "MedicalCode" },
        study: { type: "MedicalStudy" },
      },
      name: "MedicalEntity",
      subs: ["Thing"],
    },
  },
  Organization: {
    "0": {
      fields: {
        members: { type: "Organization" },
        knowsAbout: { type: "Thing" },
        correctionsPolicy: { type: "URL" },
        aggregateRating: { type: "Text" },
        hasProductReturnPolicy: { type: "Text" },
        diversityPolicy: { type: "URL" },
        duns: { type: "Text" },
        taxID: { type: "Text" },
        reviews: { type: "Text" },
        award: { type: "Text" },
        makesOffer: { type: "Text" },
        contactPoints: { type: "Text" },
        awards: { type: "Text" },
        foundingDate: { type: "Date" },
        ownershipFundingInfo: { type: "Text" },
        founders: { type: "Text" },
        seeks: { type: "Text" },
        member: { type: "Organization" },
        serviceArea: { type: "Text" },
        funder: { type: "Organization" },
        actionableFeedbackPolicy: { type: "URL" },
        areaServed: { type: "Text" },
        unnamedSourcesPolicy: { type: "URL" },
        faxNumber: { type: "Text" },
        subOrganization: { type: "Organization" },
        hasOfferCatalog: { type: "Text" },
        globalLocationNumber: { type: "Text" },
        foundingLocation: { type: "Text" },
        review: { type: "Text" },
        owns: { type: "Text" },
        sponsor: { type: "Organization" },
        event: { type: "Text" },
        founder: { type: "Text" },
        publishingPrinciples: { type: "URL" },
        isicV4: { type: "Text" },
        slogan: { type: "Text" },
        location: { type: "Text" },
        brand: { type: "Organization" },
        memberOf: { type: "Organization" },
        vatID: { type: "Text" },
        hasCredential: { type: "Text" },
        knowsLanguage: { type: "Text" },
        events: { type: "Text" },
        diversityStaffingReport: { type: "URL" },
        nonprofitStatus: { type: "Text" },
        address: { type: "Text" },
        alumni: { type: "Text" },
        dissolutionDate: { type: "Date" },
        interactionStatistic: { type: "Text" },
        logo: { type: "URL" },
        employees: { type: "Text" },
        telephone: { type: "Text" },
        hasMerchantReturnPolicy: { type: "Text" },
        email: { type: "Text" },
        department: { type: "Organization" },
        contactPoint: { type: "Text" },
        parentOrganization: { type: "Organization" },
        ethicsPolicy: { type: "URL" },
        legalName: { type: "Text" },
        leiCode: { type: "Text" },
        employee: { type: "Text" },
        numberOfEmployees: { type: "Text" },
        naics: { type: "Text" },
        hasPOS: { type: "Text" },
      },
      name: "Organization",
      subs: ["Thing"],
    },
    "1": {
      fields: {
        members: { type: "Organization" },
        knowsAbout: { type: "Thing" },
        correctionsPolicy: { type: "CreativeWork" },
        aggregateRating: { type: "AggregateRating" },
        hasProductReturnPolicy: { type: "ProductReturnPolicy" },
        diversityPolicy: { type: "CreativeWork" },
        duns: { type: "Text" },
        taxID: { type: "Text" },
        reviews: { type: "Review" },
        award: { type: "Text" },
        makesOffer: { type: "Offer" },
        contactPoints: { type: "ContactPoint" },
        awards: { type: "Text" },
        foundingDate: { type: "Date" },
        ownershipFundingInfo: { type: "CreativeWork" },
        founders: { type: "Person" },
        seeks: { type: "Demand" },
        member: { type: "Organization" },
        serviceArea: { type: "Place" },
        funder: { type: "Organization" },
        actionableFeedbackPolicy: { type: "CreativeWork" },
        areaServed: { type: "Place" },
        unnamedSourcesPolicy: { type: "CreativeWork" },
        faxNumber: { type: "Text" },
        subOrganization: { type: "Organization" },
        hasOfferCatalog: { type: "OfferCatalog" },
        globalLocationNumber: { type: "Text" },
        foundingLocation: { type: "Place" },
        review: { type: "Review" },
        owns: { type: "Product" },
        sponsor: { type: "Organization" },
        event: { type: "Event" },
        founder: { type: "Person" },
        publishingPrinciples: { type: "CreativeWork" },
        isicV4: { type: "Text" },
        slogan: { type: "Text" },
        location: { type: "Place" },
        brand: { type: "Organization" },
        memberOf: { type: "Organization" },
        vatID: { type: "Text" },
        hasCredential: { type: "EducationalOccupationalCredential" },
        knowsLanguage: { type: "Language" },
        events: { type: "Event" },
        diversityStaffingReport: { type: "Article" },
        nonprofitStatus: { type: "NonprofitType" },
        address: { type: "PostalAddress" },
        alumni: { type: "Person" },
        dissolutionDate: { type: "Date" },
        interactionStatistic: { type: "InteractionCounter" },
        logo: { type: "ImageObject" },
        employees: { type: "Person" },
        telephone: { type: "Text" },
        hasMerchantReturnPolicy: { type: "MerchantReturnPolicy" },
        email: { type: "Text" },
        department: { type: "Organization" },
        contactPoint: { type: "ContactPoint" },
        parentOrganization: { type: "Organization" },
        ethicsPolicy: { type: "CreativeWork" },
        legalName: { type: "Text" },
        leiCode: { type: "Text" },
        employee: { type: "Person" },
        numberOfEmployees: { type: "QuantitativeValue" },
        naics: { type: "Text" },
        hasPOS: { type: "Place" },
      },
      name: "Organization",
      subs: ["Thing"],
    },
  },
  Person: {
    "0": {
      fields: {
        birthPlace: { type: "Text" },
        gender: { type: "Text" },
        knowsAbout: { type: "Thing" },
        alumniOf: { type: "Text" },
        homeLocation: { type: "Text" },
        duns: { type: "Text" },
        taxID: { type: "Text" },
        award: { type: "Text" },
        birthDate: { type: "Date" },
        makesOffer: { type: "Text" },
        netWorth: { type: "Text" },
        contactPoints: { type: "Text" },
        awards: { type: "Text" },
        familyName: { type: "Text" },
        sibling: { type: "Person" },
        seeks: { type: "Text" },
        spouse: { type: "Person" },
        funder: { type: "Person" },
        colleagues: { type: "Person" },
        height: { type: "Text" },
        workLocation: { type: "Text" },
        callSign: { type: "Text" },
        faxNumber: { type: "Text" },
        children: { type: "Person" },
        hasOccupation: { type: "Text" },
        jobTitle: { type: "Text" },
        hasOfferCatalog: { type: "Text" },
        globalLocationNumber: { type: "Text" },
        deathPlace: { type: "Text" },
        owns: { type: "Text" },
        sponsor: { type: "Person" },
        deathDate: { type: "Date" },
        affiliation: { type: "Text" },
        publishingPrinciples: { type: "URL" },
        isicV4: { type: "Text" },
        brand: { type: "Text" },
        memberOf: { type: "Text" },
        honorificSuffix: { type: "Text" },
        nationality: { type: "Text" },
        vatID: { type: "Text" },
        hasCredential: { type: "Text" },
        knowsLanguage: { type: "Text" },
        relatedTo: { type: "Person" },
        follows: { type: "Person" },
        knows: { type: "Person" },
        worksFor: { type: "Text" },
        address: { type: "Text" },
        performerIn: { type: "Text" },
        honorificPrefix: { type: "Text" },
        additionalName: { type: "Text" },
        interactionStatistic: { type: "Text" },
        siblings: { type: "Person" },
        parents: { type: "Person" },
        telephone: { type: "Text" },
        weight: { type: "Text" },
        email: { type: "Text" },
        contactPoint: { type: "Text" },
        colleague: { type: "Person" },
        givenName: { type: "Text" },
        parent: { type: "Person" },
        naics: { type: "Text" },
        hasPOS: { type: "Text" },
      },
      name: "Person",
      subs: ["Thing"],
    },
    "1": {
      fields: {
        birthPlace: { type: "Place" },
        gender: { type: "Text", enums: ["Male", "Female"] },
        knowsAbout: { type: "Thing" },
        alumniOf: { type: "EducationalOrganization" },
        homeLocation: { type: "Place" },
        duns: { type: "Text" },
        taxID: { type: "Text" },
        award: { type: "Text" },
        birthDate: { type: "Date" },
        makesOffer: { type: "Offer" },
        netWorth: { type: "PriceSpecification" },
        contactPoints: { type: "ContactPoint" },
        awards: { type: "Text" },
        familyName: { type: "Text" },
        sibling: { type: "Person" },
        seeks: { type: "Demand" },
        spouse: { type: "Person" },
        funder: { type: "Person" },
        colleagues: { type: "Person" },
        height: { type: "Distance" },
        workLocation: { type: "Place" },
        callSign: { type: "Text" },
        faxNumber: { type: "Text" },
        children: { type: "Person" },
        hasOccupation: { type: "Occupation" },
        jobTitle: { type: "DefinedTerm" },
        hasOfferCatalog: { type: "OfferCatalog" },
        globalLocationNumber: { type: "Text" },
        deathPlace: { type: "Place" },
        owns: { type: "Product" },
        sponsor: { type: "Person" },
        deathDate: { type: "Date" },
        affiliation: { type: "Organization" },
        publishingPrinciples: { type: "CreativeWork" },
        isicV4: { type: "Text" },
        brand: { type: "Organization" },
        memberOf: { type: "Organization" },
        honorificSuffix: { type: "Text" },
        nationality: { type: "Country" },
        vatID: { type: "Text" },
        hasCredential: { type: "EducationalOccupationalCredential" },
        knowsLanguage: { type: "Language" },
        relatedTo: { type: "Person" },
        follows: { type: "Person" },
        knows: { type: "Person" },
        worksFor: { type: "Organization" },
        address: { type: "PostalAddress" },
        performerIn: { type: "Event" },
        honorificPrefix: { type: "Text" },
        additionalName: { type: "Text" },
        interactionStatistic: { type: "InteractionCounter" },
        siblings: { type: "Person" },
        parents: { type: "Person" },
        telephone: { type: "Text" },
        weight: { type: "QuantitativeValue" },
        email: { type: "Text" },
        contactPoint: { type: "ContactPoint" },
        colleague: { type: "Person" },
        givenName: { type: "Text" },
        parent: { type: "Person" },
        naics: { type: "Text" },
        hasPOS: { type: "Place" },
      },
      name: "Person",
      subs: ["Thing"],
    },
  },
  Place: {
    "0": {
      fields: {
        maximumAttendeeCapacity: { type: "Text" },
        geoCrosses: { type: "Place" },
        aggregateRating: { type: "Text" },
        reviews: { type: "Text" },
        photos: { type: "Text" },
        map: { type: "URL" },
        geoCoveredBy: { type: "Place" },
        branchCode: { type: "Text" },
        hasMap: { type: "URL" },
        longitude: { type: "Text" },
        additionalProperty: { type: "Text" },
        containedIn: { type: "Place" },
        geoWithin: { type: "Place" },
        hasDriveThroughService: {
          type: "Boolean",
        },
        geoContains: { type: "Place" },
        latitude: { type: "Text" },
        openingHoursSpecification: { type: "Text" },
        faxNumber: { type: "Text" },
        geoIntersects: { type: "Place" },
        geoOverlaps: { type: "Place" },
        smokingAllowed: { type: "Boolean" },
        globalLocationNumber: { type: "Text" },
        review: { type: "Text" },
        event: { type: "Text" },
        containsPlace: { type: "Place" },
        geoTouches: { type: "Place" },
        geoDisjoint: { type: "Place" },
        isicV4: { type: "Text" },
        slogan: { type: "Text" },
        containedInPlace: { type: "Place" },
        photo: { type: "Text" },
        events: { type: "Text" },
        isAccessibleForFree: { type: "Boolean" },
        publicAccess: { type: "Boolean" },
        maps: { type: "URL" },
        address: { type: "Text" },
        tourBookingPage: { type: "URL" },
        specialOpeningHoursSpecification: { type: "Text" },
        logo: { type: "URL" },
        amenityFeature: { type: "Text" },
        telephone: { type: "Text" },
        geo: { type: "Text" },
        geoCovers: { type: "Place" },
        geoEquals: { type: "Place" },
      },
      name: "Place",
      subs: ["Thing"],
    },
    "1": {
      fields: {
        maximumAttendeeCapacity: { type: "Integer" },
        geoCrosses: { type: "Place" },
        aggregateRating: { type: "AggregateRating" },
        reviews: { type: "Review" },
        photos: { type: "Photograph" },
        map: { type: "URL" },
        geoCoveredBy: { type: "Place" },
        branchCode: { type: "Text" },
        hasMap: { type: "Map" },
        longitude: { type: "Text" },
        additionalProperty: { type: "PropertyValue" },
        containedIn: { type: "Place" },
        geoWithin: { type: "Place" },
        hasDriveThroughService: {
          type: "Boolean",
        },
        geoContains: { type: "Place" },
        latitude: { type: "Text" },
        openingHoursSpecification: { type: "OpeningHoursSpecification" },
        faxNumber: { type: "Text" },
        geoIntersects: { type: "Place" },
        geoOverlaps: { type: "Place" },
        smokingAllowed: { type: "Boolean" },
        globalLocationNumber: { type: "Text" },
        review: { type: "Review" },
        event: { type: "Event" },
        containsPlace: { type: "Place" },
        geoTouches: { type: "Place" },
        geoDisjoint: { type: "Place" },
        isicV4: { type: "Text" },
        slogan: { type: "Text" },
        containedInPlace: { type: "Place" },
        photo: { type: "Photograph" },
        events: { type: "Event" },
        isAccessibleForFree: { type: "Boolean" },
        publicAccess: { type: "Boolean" },
        maps: { type: "URL" },
        address: { type: "PostalAddress" },
        tourBookingPage: { type: "URL" },
        specialOpeningHoursSpecification: {
          type: "OpeningHoursSpecification",
        },
        logo: { type: "ImageObject" },
        amenityFeature: { type: "LocationFeatureSpecification" },
        telephone: { type: "Text" },
        geo: { type: "GeoShape" },
        geoCovers: { type: "Place" },
        geoEquals: { type: "Place" },
      },
      name: "Place",
      subs: ["Thing"],
    },
  },
  Product: {
    "0": {
      fields: {
        inProductGroupWithID: { type: "Text" },
        model: { type: "Text" },
        aggregateRating: { type: "Text" },
        isConsumableFor: { type: "Product" }, // Beautiful. This is when you know it's working.
        hasProductReturnPolicy: { type: "Text" },
        reviews: { type: "Text" },
        offers: { type: "Text" },
        award: { type: "Text" },
        category: { type: "Thing" },
        width: { type: "Text" },
        awards: { type: "Text" },
        additionalProperty: { type: "Text" },
        nsn: { type: "Text" },
        manufacturer: { type: "Text" },
        sku: { type: "Text" },
        mpn: { type: "Text" },
        audience: { type: "Text" },
        height: { type: "Text" },
        gtin8: { type: "Text" },
        review: { type: "Text" },
        depth: { type: "Text" },
        productionDate: { type: "Date" },
        purchaseDate: { type: "Date" },
        itemCondition: { type: "Text" },
        slogan: { type: "Text" },
        brand: { type: "Text" },
        releaseDate: { type: "Date" },
        isAccessoryOrSparePartFor: { type: "Product" }, // Beautiful. This is when you know it's working.
        logo: { type: "URL" },
        isVariantOf: { type: "Text" },
        gtin13: { type: "Text" },
        gtin12: { type: "Text" },
        gtin14: { type: "Text" },
        material: { type: "Product" }, // Beautiful. This is when you know it's working.
        hasMerchantReturnPolicy: { type: "Text" },
        weight: { type: "Text" },
        isSimilarTo: { type: "Product" }, // Beautiful. This is when you know it's working.
        pattern: { type: "Text" },
        size: { type: "Text" },
        gtin: { type: "Text" },
        color: { type: "Text" },
        isRelatedTo: { type: "Product" }, // Beautiful. This is when you know it's working.
        productID: { type: "Text" },
      },
      name: "Product",
      subs: ["Thing"],
    },
    "1": {
      fields: {
        inProductGroupWithID: { type: "Text" },
        model: { type: "ProductModel" },
        aggregateRating: { type: "AggregateRating" },
        isConsumableFor: { type: "Product" },
        hasProductReturnPolicy: { type: "ProductReturnPolicy" },
        reviews: { type: "Review" },
        offers: { type: "Offer" },
        award: { type: "Text" },
        category: { type: "Thing" },
        width: { type: "Distance" },
        awards: { type: "Text" },
        additionalProperty: { type: "PropertyValue" },
        nsn: { type: "Text" },
        manufacturer: { type: "Organization" },
        sku: { type: "Text" },
        mpn: { type: "Text" },
        audience: { type: "Text", enums: ["Researcher"] },
        height: { type: "Distance" },
        gtin8: { type: "Text" },
        review: { type: "Review" },
        depth: { type: "Distance" },
        productionDate: { type: "Date" },
        purchaseDate: { type: "Date" },
        itemCondition: {
          type: "Text",
          enums: [
            "DamagedCondition",
            "RefurbishedCondition",
            "UsedCondition",
            "NewCondition",
          ],
        },
        slogan: { type: "Text" },
        brand: { type: "Organization" },
        releaseDate: { type: "Date" },
        isAccessoryOrSparePartFor: { type: "Product" },
        logo: { type: "ImageObject" },
        isVariantOf: { type: "ProductModel" },
        gtin13: { type: "Text" },
        gtin12: { type: "Text" },
        gtin14: { type: "Text" },
        material: { type: "Product" },
        hasMerchantReturnPolicy: { type: "MerchantReturnPolicy" },
        weight: { type: "QuantitativeValue" },
        isSimilarTo: { type: "Product" },
        pattern: { type: "DefinedTerm" },
        size: { type: "QuantitativeValue" },
        gtin: { type: "Text" },
        color: { type: "Text" },
        isRelatedTo: { type: "Product" },
        productID: { type: "Text" },
      },
      name: "Product",
      subs: ["Thing"],
    },
  },
  Audiobook: {
    "0": {
      fields: {
        readBy: { type: "Text" },
        duration: { type: "Text" },
      },
      name: "Audiobook",
      subs: ["Thing", "MediaObject", "CreativeWork", "AudioObject", "Book"],
    },
    "1": {
      fields: {
        readBy: { type: "Person" },
        duration: { type: "Duration" },
      },
      name: "Audiobook",
      subs: ["Thing", "MediaObject", "CreativeWork", "AudioObject", "Book"],
    },
  },
  ArriveAction: {
    "0": {
      fields: {},
      name: "ArriveAction",
      subs: ["Thing", "Action", "MoveAction"],
    },
    "1": {
      fields: {},
      name: "ArriveAction",
      subs: ["Thing", "Action", "MoveAction"],
    },
  },
  MedicalOrganization: {
    "0": {
      fields: {
        healthPlanNetworkId: { type: "Text" },
        medicalSpecialty: { type: "Text" },
        isAcceptingNewPatients: { type: "Boolean" },
      },
      name: "MedicalOrganization",
      subs: ["Thing", "Organization"],
    },
    "1": {
      fields: {
        healthPlanNetworkId: { type: "Text" },
        medicalSpecialty: {
          type: "Text",
          enums: [
            "PrimaryCare",
            "SpeechPathology",
            "Genetic",
            "Rheumatologic",
            "Anesthesia",
            "Emergency",
            "Gynecologic",
            "Surgical",
            "Dentistry",
            "Nursing",
            "Hematologic",
            "Pulmonary",
            "Neurologic",
            "PharmacySpecialty",
            "PublicHealth",
            "Geriatric",
            "Podiatric",
            "Urologic",
            "Midwifery",
            "Musculoskeletal",
            "Dermatology",
            "DietNutrition",
            "Physiotherapy",
            "RespiratoryTherapy",
            "Psychiatric",
            "CommunityHealth",
            "Cardiovascular",
            "Toxicologic",
            "Gastroenterologic",
            "Oncologic",
            "Renal",
            "Dermatologic",
            "PlasticSurgery",
            "LaboratoryScience",
            "Obstetric",
            "Otolaryngologic",
            "Endocrine",
            "Pathology",
            "Infectious",
            "Optometric",
            "Pediatric",
            "Radiography",
          ],
        },
        isAcceptingNewPatients: { type: "Boolean" },
      },
      name: "MedicalOrganization",
      subs: ["Thing", "Organization"],
    },
  },
  ProductGroup: {
    "0": {
      fields: {
        productGroupID: { type: "Text" },
        hasVariant: { type: "Product" },
        variesBy: { type: "Text" },
      },
      name: "ProductGroup",
      subs: ["Thing", "Product"],
    },
    "1": {
      fields: {
        productGroupID: { type: "Text" },
        hasVariant: { type: "Product" },
        variesBy: { type: "DefinedTerm" },
      },
      name: "ProductGroup",
      subs: ["Thing", "Product"],
    },
  },
})) {
  describe(`class | Crispr | ${model} modelMaker in space`, () => {
    for (let [depth, expectModelMade] of Object.entries(tests)) {
      it(`${model} at depth ${depth}`, () => {
        let modelsMined = this.crispr.modelMiner([model], depth)
        let modelMade = this.crispr.modelMaker(model, modelsMined, {
          help: false,
        })
        if (debug) {
          if (!this.jay.hasOwnProperty(model)) this.jay[model] = {}
          this.jay[model][depth] = modelMade
        }
        modelMade.should.be.eql(expectModelMade)
      })
    }
  })
}
