"use strict"
const should = require("chai").should()
const fs = require("fs")

const ThingBuilder = require("../thing-builder")
const { schemaDomainUrl } = require("../utils/get-schema")

let debug = false

before(() => {
  this.thingBuilder = new ThingBuilder(
    "schemaorg/data/releases/9.0/schemaorg-all-http",
    schemaDomainUrl
  )
  if (debug) this.jay = {}
})

after(() => {
  if (debug && this.jay) {
    fs.writeFileSync(`./expected.json`, JSON.stringify(this.jay))
  }
})

for (let [model, tests] of Object.entries({
  Thing: {
    0: {
      fields: {
        potentialAction: { type: "Text" },
        identifier: { type: "Text" },
        sameAs: { type: "URL" },
        url: { type: "URL" },
        image: { type: "URL" },
        alternateName: { type: "Text" },
        name: { type: "Text" },
        description: { type: "Text" },
        mainEntityOfPage: { type: "URL" },
        disambiguatingDescription: { type: "Text" },
        subjectOf: { type: "Text" },
        additionalType: { type: "URL" }
      },
      name: "Thing",
      subs: []
    },
    1: {
      fields: {
        potentialAction: { type: "Action", foreign: true },
        identifier: { type: "PropertyValue", foreign: true },
        sameAs: { type: "URL" },
        url: { type: "URL" },
        image: { type: "ImageObject", foreign: true },
        alternateName: { type: "Text" },
        name: { type: "Text" },
        description: { type: "Text" },
        mainEntityOfPage: { type: "CreativeWork", foreign: true },
        disambiguatingDescription: { type: "Text" },
        subjectOf: { type: "CreativeWork", foreign: true },
        additionalType: { type: "URL" }
      },
      name: "Thing",
      subs: []
    }
  },
  Action: {
    0: {
      fields: {
        instrument: { type: "Thing", foreign: true },
        endTime: { type: "Time" },
        participant: { type: "Text" },
        result: { type: "Thing", foreign: true },
        startTime: { type: "Time" },
        actionStatus: {
          type: "Text",
          enums: [
            "FailedActionStatus",
            "CompletedActionStatus",
            "ActiveActionStatus",
            "PotentialActionStatus"
          ]
        },
        target: { type: "Text" },
        agent: { type: "Text" },
        error: { type: "Thing", foreign: true },
        location: { type: "Text" },
        object: { type: "Thing", foreign: true }
      },
      name: "Action",
      subs: ["Thing"]
    },
    1: {
      fields: {
        instrument: { type: "Thing", foreign: true },
        endTime: { type: "Time" },
        participant: { type: "Person", foreign: true },
        result: { type: "Thing", foreign: true },
        startTime: { type: "Time" },
        actionStatus: {
          type: "Text",
          enums: [
            "FailedActionStatus",
            "CompletedActionStatus",
            "ActiveActionStatus",
            "PotentialActionStatus"
          ]
        },
        target: { type: "EntryPoint", foreign: true },
        agent: { type: "Person", foreign: true },
        error: { type: "Thing", foreign: true },
        location: { type: "PostalAddress", foreign: true },
        object: { type: "Thing", foreign: true }
      },
      name: "Action",
      subs: ["Thing"]
    }
  },
  CreativeWork: {
    0: {
      fields: {
        typicalAgeRange: { type: "Text" },
        hasPart: { type: "CreativeWork", foreign: true },
        sdDatePublished: { type: "Date" },
        educationalLevel: { type: "Text" },
        releasedEvent: { type: "Text" },
        schemaVersion: { type: "Text" },
        contentLocation: { type: "Text" },
        locationCreated: { type: "Text" },
        aggregateRating: { type: "Text" },
        temporalCoverage: { type: "Text" },
        accessModeSufficient: { type: "Text" },
        accountablePerson: { type: "Text" },
        mainEntity: { type: "Thing", foreign: true },
        sdPublisher: { type: "Text" },
        spatialCoverage: { type: "Text" },
        reviews: { type: "Text" },
        exampleOfWork: { type: "CreativeWork", foreign: true },
        maintainer: { type: "Text" },
        editor: { type: "Text" },
        offers: { type: "Text" },
        discussionUrl: { type: "URL" },
        award: { type: "Text" },
        sdLicense: { type: "CreativeWork", foreign: true },
        copyrightHolder: { type: "Text" },
        accessibilityHazard: { type: "Text" },
        copyrightYear: { type: "Number" },
        awards: { type: "Text" },
        publisherImprint: { type: "Text" },
        commentCount: { type: "Integer" },
        spatial: { type: "Text" },
        recordedAt: { type: "Text" },
        abstract: { type: "Text" },
        fileFormat: { type: "Text" },
        isPartOf: { type: "CreativeWork", foreign: true },
        temporal: { type: "Text" },
        accessibilitySummary: { type: "Text" },
        inLanguage: { type: "Text" },
        educationalAlignment: { type: "Text" },
        associatedMedia: { type: "Text" },
        funder: { type: "Text" },
        position: { type: "Text" },
        audio: { type: "Text" },
        workExample: { type: "CreativeWork", foreign: true },
        encoding: { type: "Text" },
        interactivityType: { type: "Text" },
        provider: { type: "Text" },
        character: { type: "Text" },
        sourceOrganization: { type: "Text" },
        audience: { type: "Text", enums: ["Researcher"] },
        materialExtent: { type: "Text" },
        video: { type: "Text" },
        accessibilityFeature: { type: "Text" },
        publisher: { type: "Text" },
        text: { type: "Text" },
        publication: { type: "Text" },
        contributor: { type: "Text" },
        encodingFormat: { type: "Text" },
        review: { type: "Text" },
        accessibilityControl: { type: "Text" },
        license: { type: "CreativeWork", foreign: true },
        sponsor: { type: "Text" },
        encodings: { type: "Text" },
        about: { type: "Thing", foreign: true },
        isBasedOn: { type: "CreativeWork", foreign: true },
        creator: { type: "Text" },
        publishingPrinciples: { type: "CreativeWork", foreign: true },
        producer: { type: "Text" },
        correction: { type: "Text" },
        workTranslation: { type: "CreativeWork", foreign: true },
        mentions: { type: "Thing", foreign: true },
        contentReferenceTime: { type: "DateTime" },
        dateCreated: { type: "Date" },
        educationalUse: { type: "Text" },
        teaches: { type: "Text" },
        alternativeHeadline: { type: "Text" },
        datePublished: { type: "Date" },
        isAccessibleForFree: { type: "Boolean" },
        headline: { type: "Text" },
        translationOfWork: { type: "CreativeWork", foreign: true },
        acquireLicensePage: { type: "CreativeWork", foreign: true },
        conditionsOfAccess: { type: "Text" },
        citation: { type: "CreativeWork", foreign: true },
        accessibilityAPI: { type: "Text" },
        interactionStatistic: { type: "Text" },
        contentRating: { type: "Text" },
        accessMode: { type: "Text" },
        material: { type: "Text" },
        isFamilyFriendly: { type: "Boolean" },
        assesses: { type: "Text" },
        keywords: { type: "Text" },
        version: { type: "Text" },
        dateModified: { type: "Date" },
        learningResourceType: { type: "Text" },
        genre: { type: "Text" },
        creativeWorkStatus: { type: "Text" },
        pattern: { type: "Text" },
        editEIDR: { type: "Text" },
        author: { type: "Text" },
        size: { type: "Text" },
        translator: { type: "Text" },
        timeRequired: { type: "Text" },
        usageInfo: { type: "CreativeWork", foreign: true },
        isBasedOnUrl: { type: "CreativeWork", foreign: true },
        thumbnailUrl: { type: "URL" },
        expires: { type: "Date" },
        comment: { type: "Text" }
      },
      name: "CreativeWork",
      subs: ["Thing"]
    },
    1: {
      fields: {
        typicalAgeRange: { type: "Text" },
        hasPart: { type: "CreativeWork", foreign: true },
        sdDatePublished: { type: "Date" },
        educationalLevel: { type: "DefinedTerm", foreign: true },
        releasedEvent: { type: "PublicationEvent", foreign: true },
        schemaVersion: { type: "Text" },
        contentLocation: { type: "Place", foreign: true },
        locationCreated: { type: "Place", foreign: true },
        aggregateRating: { type: "AggregateRating", foreign: true },
        temporalCoverage: { type: "Text" },
        accessModeSufficient: { type: "ItemList", foreign: true },
        accountablePerson: { type: "Person", foreign: true },
        mainEntity: { type: "Thing", foreign: true },
        sdPublisher: { type: "Person", foreign: true },
        spatialCoverage: { type: "Place", foreign: true },
        reviews: { type: "Review", foreign: true },
        exampleOfWork: { type: "CreativeWork", foreign: true },
        maintainer: { type: "Person", foreign: true },
        editor: { type: "Person", foreign: true },
        offers: { type: "Offer", foreign: true },
        discussionUrl: { type: "URL" },
        award: { type: "Text" },
        sdLicense: { type: "CreativeWork", foreign: true },
        copyrightHolder: { type: "Person", foreign: true },
        accessibilityHazard: { type: "Text" },
        copyrightYear: { type: "Number" },
        awards: { type: "Text" },
        publisherImprint: { type: "Organization", foreign: true },
        commentCount: { type: "Integer" },
        spatial: { type: "Place", foreign: true },
        recordedAt: { type: "Event", foreign: true },
        abstract: { type: "Text" },
        fileFormat: { type: "Text" },
        isPartOf: { type: "CreativeWork", foreign: true },
        temporal: { type: "Text" },
        accessibilitySummary: { type: "Text" },
        inLanguage: { type: "Language", foreign: true },
        educationalAlignment: { type: "AlignmentObject", foreign: true },
        associatedMedia: { type: "MediaObject", foreign: true },
        funder: { type: "Person", foreign: true },
        position: { type: "Text" },
        audio: { type: "AudioObject", foreign: true },
        workExample: { type: "CreativeWork", foreign: true },
        encoding: { type: "MediaObject", foreign: true },
        interactivityType: { type: "Text" },
        provider: { type: "Person", foreign: true },
        character: { type: "Person", foreign: true },
        sourceOrganization: { type: "Organization", foreign: true },
        audience: { type: "Text", enums: ["Researcher"] },
        materialExtent: { type: "QuantitativeValue", foreign: true },
        video: { type: "Clip", foreign: true },
        accessibilityFeature: { type: "Text" },
        publisher: { type: "Person", foreign: true },
        text: { type: "Text" },
        publication: { type: "PublicationEvent", foreign: true },
        contributor: { type: "Person", foreign: true },
        encodingFormat: { type: "Text" },
        review: { type: "Review", foreign: true },
        accessibilityControl: { type: "Text" },
        license: { type: "CreativeWork", foreign: true },
        sponsor: { type: "Person", foreign: true },
        encodings: { type: "MediaObject", foreign: true },
        about: { type: "Thing", foreign: true },
        isBasedOn: { type: "CreativeWork", foreign: true },
        creator: { type: "Person", foreign: true },
        publishingPrinciples: { type: "CreativeWork", foreign: true },
        producer: { type: "Person", foreign: true },
        correction: { type: "CorrectionComment", foreign: true },
        workTranslation: { type: "CreativeWork", foreign: true },
        mentions: { type: "Thing", foreign: true },
        contentReferenceTime: { type: "DateTime" },
        dateCreated: { type: "Date" },
        educationalUse: { type: "Text" },
        teaches: { type: "DefinedTerm", foreign: true },
        alternativeHeadline: { type: "Text" },
        datePublished: { type: "Date" },
        isAccessibleForFree: { type: "Boolean" },
        headline: { type: "Text" },
        translationOfWork: { type: "CreativeWork", foreign: true },
        acquireLicensePage: { type: "CreativeWork", foreign: true },
        conditionsOfAccess: { type: "Text" },
        citation: { type: "CreativeWork", foreign: true },
        accessibilityAPI: { type: "Text" },
        interactionStatistic: { type: "InteractionCounter", foreign: true },
        contentRating: { type: "Rating", foreign: true },
        accessMode: { type: "Text" },
        material: { type: "Product", foreign: true },
        isFamilyFriendly: { type: "Boolean" },
        assesses: { type: "DefinedTerm", foreign: true },
        keywords: { type: "Text" },
        version: { type: "Text" },
        dateModified: { type: "Date" },
        learningResourceType: { type: "Text" },
        genre: { type: "Text" },
        creativeWorkStatus: { type: "DefinedTerm", foreign: true },
        pattern: { type: "DefinedTerm", foreign: true },
        editEIDR: { type: "Text" },
        author: { type: "Person", foreign: true },
        size: { type: "DefinedTerm", foreign: true },
        translator: { type: "Person", foreign: true },
        timeRequired: { type: "Duration", foreign: true },
        usageInfo: { type: "CreativeWork", foreign: true },
        isBasedOnUrl: { type: "CreativeWork", foreign: true },
        thumbnailUrl: { type: "URL" },
        expires: { type: "Date" },
        comment: { type: "Comment", foreign: true }
      },
      name: "CreativeWork",
      subs: ["Thing"]
    }
  },
  Event: {
    0: {
      fields: {
        maximumAttendeeCapacity: { type: "Integer" },
        typicalAgeRange: { type: "Text" },
        organizer: { type: "Text" },
        attendees: { type: "Text" },
        aggregateRating: { type: "Text" },
        subEvents: { type: "Event", foreign: true },
        offers: { type: "Text" },
        workFeatured: { type: "Text" },
        inLanguage: { type: "Text" },
        funder: { type: "Text" },
        remainingAttendeeCapacity: { type: "Integer" },
        maximumPhysicalAttendeeCapacity: { type: "Integer" },
        audience: { type: "Text", enums: ["Researcher"] },
        actor: { type: "Text" },
        performers: { type: "Text" },
        endDate: { type: "Date" },
        eventSchedule: { type: "Text" },
        doorTime: { type: "Time" },
        contributor: { type: "Text" },
        review: { type: "Text" },
        sponsor: { type: "Text" },
        about: { type: "Thing", foreign: true },
        subEvent: { type: "Event", foreign: true },
        location: { type: "Text" },
        recordedIn: { type: "Text" },
        composer: { type: "Text" },
        isAccessibleForFree: { type: "Boolean" },
        performer: { type: "Text" },
        attendee: { type: "Text" },
        workPerformed: { type: "Text" },
        eventStatus: {
          type: "Text",
          enums: [
            "EventPostponed",
            "EventMovedOnline",
            "EventRescheduled",
            "EventScheduled",
            "EventCancelled"
          ]
        },
        director: { type: "Text" },
        duration: { type: "Text" },
        maximumVirtualAttendeeCapacity: { type: "Integer" },
        translator: { type: "Text" },
        eventAttendanceMode: {
          type: "Text",
          enums: [
            "OnlineEventAttendanceMode",
            "MixedEventAttendanceMode",
            "OfflineEventAttendanceMode"
          ]
        },
        startDate: { type: "Date" },
        superEvent: { type: "Event", foreign: true },
        previousStartDate: { type: "Date" }
      },
      name: "Event",
      subs: ["Thing"]
    },
    1: {
      fields: {
        maximumAttendeeCapacity: { type: "Integer" },
        typicalAgeRange: { type: "Text" },
        organizer: { type: "Organization", foreign: true },
        attendees: { type: "Organization", foreign: true },
        aggregateRating: { type: "AggregateRating", foreign: true },
        subEvents: { type: "Event", foreign: true },
        offers: { type: "Offer", foreign: true },
        workFeatured: { type: "CreativeWork", foreign: true },
        inLanguage: { type: "Language", foreign: true },
        funder: { type: "Organization", foreign: true },
        remainingAttendeeCapacity: { type: "Integer" },
        maximumPhysicalAttendeeCapacity: { type: "Integer" },
        audience: { type: "Text", enums: ["Researcher"] },
        actor: { type: "Person", foreign: true },
        performers: { type: "Organization", foreign: true },
        endDate: { type: "Date" },
        eventSchedule: { type: "Schedule", foreign: true },
        doorTime: { type: "Time" },
        contributor: { type: "Organization", foreign: true },
        review: { type: "Review", foreign: true },
        sponsor: { type: "Organization", foreign: true },
        about: { type: "Thing", foreign: true },
        subEvent: { type: "Event", foreign: true },
        location: { type: "PostalAddress", foreign: true },
        recordedIn: { type: "CreativeWork", foreign: true },
        composer: { type: "Organization", foreign: true },
        isAccessibleForFree: { type: "Boolean" },
        performer: { type: "Organization", foreign: true },
        attendee: { type: "Organization", foreign: true },
        workPerformed: { type: "CreativeWork", foreign: true },
        eventStatus: {
          type: "Text",
          enums: [
            "EventPostponed",
            "EventMovedOnline",
            "EventRescheduled",
            "EventScheduled",
            "EventCancelled"
          ]
        },
        director: { type: "Person", foreign: true },
        duration: { type: "Duration", foreign: true },
        maximumVirtualAttendeeCapacity: { type: "Integer" },
        translator: { type: "Organization", foreign: true },
        eventAttendanceMode: {
          type: "Text",
          enums: [
            "OnlineEventAttendanceMode",
            "MixedEventAttendanceMode",
            "OfflineEventAttendanceMode"
          ]
        },
        startDate: { type: "Date" },
        superEvent: { type: "Event", foreign: true },
        previousStartDate: { type: "Date" }
      },
      name: "Event",
      subs: ["Thing"]
    }
  },
  MedicalEntity: {
    0: {
      fields: {
        medicineSystem: {
          type: "Text",
          enums: [
            "TraditionalChinese",
            "Homeopathic",
            "Osteopathic",
            "WesternConventional",
            "Ayurvedic",
            "Chiropractic"
          ]
        },
        guideline: { type: "Text" },
        relevantSpecialty: {
          type: "Text",
          enums: [
            "PrimaryCare",
            "SpeechPathology",
            "Genetic",
            "Rheumatologic",
            "Anesthesia",
            "Emergency",
            "Gynecologic",
            "Surgical",
            "Dentistry",
            "Nursing",
            "Hematologic",
            "Pulmonary",
            "Neurologic",
            "PharmacySpecialty",
            "PublicHealth",
            "Geriatric",
            "Podiatric",
            "Urologic",
            "Midwifery",
            "Musculoskeletal",
            "Dermatology",
            "DietNutrition",
            "Physiotherapy",
            "RespiratoryTherapy",
            "Psychiatric",
            "CommunityHealth",
            "Cardiovascular",
            "Toxicologic",
            "Gastroenterologic",
            "Oncologic",
            "Renal",
            "Dermatologic",
            "PlasticSurgery",
            "LaboratoryScience",
            "Obstetric",
            "Otolaryngologic",
            "Endocrine",
            "Pathology",
            "Infectious",
            "Optometric",
            "Pediatric",
            "Radiography"
          ]
        },
        legalStatus: { type: "Text" },
        recognizingAuthority: { type: "Text" },
        code: { type: "Text" },
        study: { type: "Text" }
      },
      name: "MedicalEntity",
      subs: ["Thing"]
    },
    1: {
      fields: {
        medicineSystem: {
          type: "Text",
          enums: [
            "TraditionalChinese",
            "Homeopathic",
            "Osteopathic",
            "WesternConventional",
            "Ayurvedic",
            "Chiropractic"
          ]
        },
        guideline: { type: "MedicalGuideline", foreign: true },
        relevantSpecialty: {
          type: "Text",
          enums: [
            "PrimaryCare",
            "SpeechPathology",
            "Genetic",
            "Rheumatologic",
            "Anesthesia",
            "Emergency",
            "Gynecologic",
            "Surgical",
            "Dentistry",
            "Nursing",
            "Hematologic",
            "Pulmonary",
            "Neurologic",
            "PharmacySpecialty",
            "PublicHealth",
            "Geriatric",
            "Podiatric",
            "Urologic",
            "Midwifery",
            "Musculoskeletal",
            "Dermatology",
            "DietNutrition",
            "Physiotherapy",
            "RespiratoryTherapy",
            "Psychiatric",
            "CommunityHealth",
            "Cardiovascular",
            "Toxicologic",
            "Gastroenterologic",
            "Oncologic",
            "Renal",
            "Dermatologic",
            "PlasticSurgery",
            "LaboratoryScience",
            "Obstetric",
            "Otolaryngologic",
            "Endocrine",
            "Pathology",
            "Infectious",
            "Optometric",
            "Pediatric",
            "Radiography"
          ]
        },
        legalStatus: { type: "DrugLegalStatus", foreign: true },
        recognizingAuthority: { type: "Organization", foreign: true },
        code: { type: "MedicalCode", foreign: true },
        study: { type: "MedicalStudy", foreign: true }
      },
      name: "MedicalEntity",
      subs: ["Thing"]
    }
  },
  Organization: {
    0: {
      fields: {
        members: { type: "Organization", foreign: true },
        knowsAbout: { type: "Thing", foreign: true },
        correctionsPolicy: { type: "URL" },
        aggregateRating: { type: "Text" },
        hasProductReturnPolicy: { type: "Text" },
        diversityPolicy: { type: "URL" },
        duns: { type: "Text" },
        taxID: { type: "Text" },
        reviews: { type: "Text" },
        award: { type: "Text" },
        makesOffer: { type: "Text" },
        contactPoints: { type: "Text" },
        awards: { type: "Text" },
        foundingDate: { type: "Date" },
        ownershipFundingInfo: { type: "Text" },
        founders: { type: "Text" },
        seeks: { type: "Text" },
        member: { type: "Organization", foreign: true },
        serviceArea: { type: "Text" },
        funder: { type: "Organization", foreign: true },
        actionableFeedbackPolicy: { type: "URL" },
        areaServed: { type: "Text" },
        unnamedSourcesPolicy: { type: "URL" },
        faxNumber: { type: "Text" },
        subOrganization: { type: "Organization", foreign: true },
        hasOfferCatalog: { type: "Text" },
        globalLocationNumber: { type: "Text" },
        foundingLocation: { type: "Text" },
        review: { type: "Text" },
        owns: { type: "Text" },
        sponsor: { type: "Organization", foreign: true },
        event: { type: "Text" },
        founder: { type: "Text" },
        publishingPrinciples: { type: "URL" },
        isicV4: { type: "Text" },
        slogan: { type: "Text" },
        location: { type: "Text" },
        brand: { type: "Organization", foreign: true },
        memberOf: { type: "Organization", foreign: true },
        vatID: { type: "Text" },
        hasCredential: { type: "Text" },
        knowsLanguage: { type: "Text" },
        events: { type: "Text" },
        diversityStaffingReport: { type: "URL" },
        nonprofitStatus: { type: "Text" },
        address: { type: "Text" },
        alumni: { type: "Text" },
        dissolutionDate: { type: "Date" },
        interactionStatistic: { type: "Text" },
        logo: { type: "URL" },
        employees: { type: "Text" },
        telephone: { type: "Text" },
        hasMerchantReturnPolicy: { type: "Text" },
        email: { type: "Text" },
        department: { type: "Organization", foreign: true },
        contactPoint: { type: "Text" },
        parentOrganization: { type: "Organization", foreign: true },
        ethicsPolicy: { type: "URL" },
        legalName: { type: "Text" },
        leiCode: { type: "Text" },
        employee: { type: "Text" },
        numberOfEmployees: { type: "Text" },
        naics: { type: "Text" },
        hasPOS: { type: "Text" }
      },
      name: "Organization",
      subs: ["Thing"]
    },
    1: {
      fields: {
        members: { type: "Organization", foreign: true },
        knowsAbout: { type: "Thing", foreign: true },
        correctionsPolicy: { type: "CreativeWork", foreign: true },
        aggregateRating: { type: "AggregateRating", foreign: true },
        hasProductReturnPolicy: { type: "ProductReturnPolicy", foreign: true },
        diversityPolicy: { type: "CreativeWork", foreign: true },
        duns: { type: "Text" },
        taxID: { type: "Text" },
        reviews: { type: "Review", foreign: true },
        award: { type: "Text" },
        makesOffer: { type: "Offer", foreign: true },
        contactPoints: { type: "ContactPoint", foreign: true },
        awards: { type: "Text" },
        foundingDate: { type: "Date" },
        ownershipFundingInfo: { type: "CreativeWork", foreign: true },
        founders: { type: "Person", foreign: true },
        seeks: { type: "Demand", foreign: true },
        member: { type: "Organization", foreign: true },
        serviceArea: { type: "Place", foreign: true },
        funder: { type: "Organization", foreign: true },
        actionableFeedbackPolicy: { type: "CreativeWork", foreign: true },
        areaServed: { type: "Place", foreign: true },
        unnamedSourcesPolicy: { type: "CreativeWork", foreign: true },
        faxNumber: { type: "Text" },
        subOrganization: { type: "Organization", foreign: true },
        hasOfferCatalog: { type: "OfferCatalog", foreign: true },
        globalLocationNumber: { type: "Text" },
        foundingLocation: { type: "Place", foreign: true },
        review: { type: "Review", foreign: true },
        owns: { type: "Product", foreign: true },
        sponsor: { type: "Organization", foreign: true },
        event: { type: "Event", foreign: true },
        founder: { type: "Person", foreign: true },
        publishingPrinciples: { type: "CreativeWork", foreign: true },
        isicV4: { type: "Text" },
        slogan: { type: "Text" },
        location: { type: "Place", foreign: true },
        brand: { type: "Organization", foreign: true },
        memberOf: { type: "Organization", foreign: true },
        vatID: { type: "Text" },
        hasCredential: {
          type: "EducationalOccupationalCredential",
          foreign: true
        },
        knowsLanguage: { type: "Language", foreign: true },
        events: { type: "Event", foreign: true },
        diversityStaffingReport: { type: "Article", foreign: true },
        nonprofitStatus: { type: "NonprofitType", foreign: true },
        address: { type: "PostalAddress", foreign: true },
        alumni: { type: "Person", foreign: true },
        dissolutionDate: { type: "Date" },
        interactionStatistic: { type: "InteractionCounter", foreign: true },
        logo: { type: "ImageObject", foreign: true },
        employees: { type: "Person", foreign: true },
        telephone: { type: "Text" },
        hasMerchantReturnPolicy: {
          type: "MerchantReturnPolicy",
          foreign: true
        },
        email: { type: "Text" },
        department: { type: "Organization", foreign: true },
        contactPoint: { type: "ContactPoint", foreign: true },
        parentOrganization: { type: "Organization", foreign: true },
        ethicsPolicy: { type: "CreativeWork", foreign: true },
        legalName: { type: "Text" },
        leiCode: { type: "Text" },
        employee: { type: "Person", foreign: true },
        numberOfEmployees: { type: "QuantitativeValue", foreign: true },
        naics: { type: "Text" },
        hasPOS: { type: "Place", foreign: true }
      },
      name: "Organization",
      subs: ["Thing"]
    }
  },
  Person: {
    0: {
      fields: {
        birthPlace: { type: "Text" },
        gender: { type: "Text" },
        knowsAbout: { type: "Thing", foreign: true },
        alumniOf: { type: "Text" },
        homeLocation: { type: "Text" },
        duns: { type: "Text" },
        taxID: { type: "Text" },
        award: { type: "Text" },
        birthDate: { type: "Date" },
        makesOffer: { type: "Text" },
        netWorth: { type: "Text" },
        contactPoints: { type: "Text" },
        awards: { type: "Text" },
        familyName: { type: "Text" },
        sibling: { type: "Person", foreign: true },
        seeks: { type: "Text" },
        spouse: { type: "Person", foreign: true },
        funder: { type: "Person", foreign: true },
        colleagues: { type: "Person", foreign: true },
        height: { type: "Text" },
        workLocation: { type: "Text" },
        callSign: { type: "Text" },
        faxNumber: { type: "Text" },
        children: { type: "Person", foreign: true },
        hasOccupation: { type: "Text" },
        jobTitle: { type: "Text" },
        hasOfferCatalog: { type: "Text" },
        globalLocationNumber: { type: "Text" },
        deathPlace: { type: "Text" },
        owns: { type: "Text" },
        sponsor: { type: "Person", foreign: true },
        deathDate: { type: "Date" },
        affiliation: { type: "Text" },
        publishingPrinciples: { type: "URL" },
        isicV4: { type: "Text" },
        brand: { type: "Text" },
        memberOf: { type: "Text" },
        honorificSuffix: { type: "Text" },
        nationality: { type: "Text" },
        vatID: { type: "Text" },
        hasCredential: { type: "Text" },
        knowsLanguage: { type: "Text" },
        relatedTo: { type: "Person", foreign: true },
        follows: { type: "Person", foreign: true },
        knows: { type: "Person", foreign: true },
        worksFor: { type: "Text" },
        address: { type: "Text" },
        performerIn: { type: "Text" },
        honorificPrefix: { type: "Text" },
        additionalName: { type: "Text" },
        interactionStatistic: { type: "Text" },
        siblings: { type: "Person", foreign: true },
        parents: { type: "Person", foreign: true },
        telephone: { type: "Text" },
        weight: { type: "Text" },
        email: { type: "Text" },
        contactPoint: { type: "Text" },
        colleague: { type: "Person", foreign: true },
        givenName: { type: "Text" },
        parent: { type: "Person", foreign: true },
        naics: { type: "Text" },
        hasPOS: { type: "Text" }
      },
      name: "Person",
      subs: ["Thing"]
    },
    1: {
      fields: {
        birthPlace: { type: "Place", foreign: true },
        gender: { type: "Text", enums: ["Male", "Female"] },
        knowsAbout: { type: "Thing", foreign: true },
        alumniOf: { type: "EducationalOrganization", foreign: true },
        homeLocation: { type: "Place", foreign: true },
        duns: { type: "Text" },
        taxID: { type: "Text" },
        award: { type: "Text" },
        birthDate: { type: "Date" },
        makesOffer: { type: "Offer", foreign: true },
        netWorth: { type: "PriceSpecification", foreign: true },
        contactPoints: { type: "ContactPoint", foreign: true },
        awards: { type: "Text" },
        familyName: { type: "Text" },
        sibling: { type: "Person", foreign: true },
        seeks: { type: "Demand", foreign: true },
        spouse: { type: "Person", foreign: true },
        funder: { type: "Person", foreign: true },
        colleagues: { type: "Person", foreign: true },
        height: { type: "Distance", foreign: true },
        workLocation: { type: "Place", foreign: true },
        callSign: { type: "Text" },
        faxNumber: { type: "Text" },
        children: { type: "Person", foreign: true },
        hasOccupation: { type: "Occupation", foreign: true },
        jobTitle: { type: "DefinedTerm", foreign: true },
        hasOfferCatalog: { type: "OfferCatalog", foreign: true },
        globalLocationNumber: { type: "Text" },
        deathPlace: { type: "Place", foreign: true },
        owns: { type: "Product", foreign: true },
        sponsor: { type: "Person", foreign: true },
        deathDate: { type: "Date" },
        affiliation: { type: "Organization", foreign: true },
        publishingPrinciples: { type: "CreativeWork", foreign: true },
        isicV4: { type: "Text" },
        brand: { type: "Organization", foreign: true },
        memberOf: { type: "Organization", foreign: true },
        honorificSuffix: { type: "Text" },
        nationality: { type: "Country", foreign: true },
        vatID: { type: "Text" },
        hasCredential: {
          type: "EducationalOccupationalCredential",
          foreign: true
        },
        knowsLanguage: { type: "Language", foreign: true },
        relatedTo: { type: "Person", foreign: true },
        follows: { type: "Person", foreign: true },
        knows: { type: "Person", foreign: true },
        worksFor: { type: "Organization", foreign: true },
        address: { type: "PostalAddress", foreign: true },
        performerIn: { type: "Event", foreign: true },
        honorificPrefix: { type: "Text" },
        additionalName: { type: "Text" },
        interactionStatistic: { type: "InteractionCounter", foreign: true },
        siblings: { type: "Person", foreign: true },
        parents: { type: "Person", foreign: true },
        telephone: { type: "Text" },
        weight: { type: "QuantitativeValue", foreign: true },
        email: { type: "Text" },
        contactPoint: { type: "ContactPoint", foreign: true },
        colleague: { type: "Person", foreign: true },
        givenName: { type: "Text" },
        parent: { type: "Person", foreign: true },
        naics: { type: "Text" },
        hasPOS: { type: "Place", foreign: true }
      },
      name: "Person",
      subs: ["Thing"]
    }
  },
  Place: {
    0: {
      fields: {
        maximumAttendeeCapacity: { type: "Integer" },
        geoCrosses: { type: "Place", foreign: true },
        aggregateRating: { type: "Text" },
        reviews: { type: "Text" },
        photos: { type: "Text" },
        map: { type: "URL" },
        geoCoveredBy: { type: "Place", foreign: true },
        branchCode: { type: "Text" },
        hasMap: { type: "URL" },
        longitude: { type: "Text" },
        additionalProperty: { type: "Text" },
        containedIn: { type: "Place", foreign: true },
        geoWithin: { type: "Place", foreign: true },
        hasDriveThroughService: {
          type: "Boolean"
        },
        geoContains: { type: "Place", foreign: true },
        latitude: { type: "Text" },
        openingHoursSpecification: { type: "Text" },
        faxNumber: { type: "Text" },
        geoIntersects: { type: "Place", foreign: true },
        geoOverlaps: { type: "Place", foreign: true },
        smokingAllowed: { type: "Boolean" },
        globalLocationNumber: { type: "Text" },
        review: { type: "Text" },
        event: { type: "Text" },
        containsPlace: { type: "Place", foreign: true },
        geoTouches: { type: "Place", foreign: true },
        geoDisjoint: { type: "Place", foreign: true },
        isicV4: { type: "Text" },
        slogan: { type: "Text" },
        containedInPlace: { type: "Place", foreign: true },
        photo: { type: "Text" },
        events: { type: "Text" },
        isAccessibleForFree: { type: "Boolean" },
        publicAccess: { type: "Boolean" },
        maps: { type: "URL" },
        address: { type: "Text" },
        tourBookingPage: { type: "URL" },
        specialOpeningHoursSpecification: { type: "Text" },
        logo: { type: "URL" },
        amenityFeature: { type: "Text" },
        telephone: { type: "Text" },
        geo: { type: "Text" },
        geoCovers: { type: "Place", foreign: true },
        geoEquals: { type: "Place", foreign: true }
      },
      name: "Place",
      subs: ["Thing"]
    },
    1: {
      fields: {
        maximumAttendeeCapacity: { type: "Integer" },
        geoCrosses: { type: "Place", foreign: true },
        aggregateRating: { type: "AggregateRating", foreign: true },
        reviews: { type: "Review", foreign: true },
        photos: { type: "Photograph", foreign: true },
        map: { type: "URL" },
        geoCoveredBy: { type: "Place", foreign: true },
        branchCode: { type: "Text" },
        hasMap: { type: "Map", foreign: true },
        longitude: { type: "Text" },
        additionalProperty: { type: "PropertyValue", foreign: true },
        containedIn: { type: "Place", foreign: true },
        geoWithin: { type: "Place", foreign: true },
        hasDriveThroughService: {
          type: "Boolean"
        },
        geoContains: { type: "Place", foreign: true },
        latitude: { type: "Text" },
        openingHoursSpecification: {
          type: "OpeningHoursSpecification",
          foreign: true
        },
        faxNumber: { type: "Text" },
        geoIntersects: { type: "Place", foreign: true },
        geoOverlaps: { type: "Place", foreign: true },
        smokingAllowed: { type: "Boolean" },
        globalLocationNumber: { type: "Text" },
        review: { type: "Review", foreign: true },
        event: { type: "Event", foreign: true },
        containsPlace: { type: "Place", foreign: true },
        geoTouches: { type: "Place", foreign: true },
        geoDisjoint: { type: "Place", foreign: true },
        isicV4: { type: "Text" },
        slogan: { type: "Text" },
        containedInPlace: { type: "Place", foreign: true },
        photo: { type: "Photograph", foreign: true },
        events: { type: "Event", foreign: true },
        isAccessibleForFree: { type: "Boolean" },
        publicAccess: { type: "Boolean" },
        maps: { type: "URL" },
        address: { type: "PostalAddress", foreign: true },
        tourBookingPage: { type: "URL" },
        specialOpeningHoursSpecification: {
          type: "OpeningHoursSpecification",
          foreign: true
        },
        logo: { type: "ImageObject", foreign: true },
        amenityFeature: { type: "LocationFeatureSpecification", foreign: true },
        telephone: { type: "Text" },
        geo: { type: "GeoShape", foreign: true },
        geoCovers: { type: "Place", foreign: true },
        geoEquals: { type: "Place", foreign: true }
      },
      name: "Place",
      subs: ["Thing"]
    }
  },
  Product: {
    0: {
      fields: {
        inProductGroupWithID: { type: "Text" },
        model: { type: "Text" },
        aggregateRating: { type: "Text" },
        isConsumableFor: { type: "Product", foreign: true }, // Beautiful. This is when you know it's working.
        hasProductReturnPolicy: { type: "Text" },
        reviews: { type: "Text" },
        offers: { type: "Text" },
        award: { type: "Text" },
        category: { type: "Thing", foreign: true },
        width: { type: "Text" },
        awards: { type: "Text" },
        additionalProperty: { type: "Text" },
        nsn: { type: "Text" },
        manufacturer: { type: "Text" },
        sku: { type: "Text" },
        mpn: { type: "Text" },
        audience: { type: "Text", enums: ["Researcher"] },
        height: { type: "Text" },
        gtin8: { type: "Text" },
        review: { type: "Text" },
        depth: { type: "Text" },
        productionDate: { type: "Date" },
        purchaseDate: { type: "Date" },
        itemCondition: {
          type: "Text",
          enums: [
            "DamagedCondition",
            "RefurbishedCondition",
            "UsedCondition",
            "NewCondition"
          ]
        },
        slogan: { type: "Text" },
        brand: { type: "Text" },
        releaseDate: { type: "Date" },
        isAccessoryOrSparePartFor: { type: "Product", foreign: true }, // Beautiful. This is when you know it's working.
        logo: { type: "URL" },
        isVariantOf: { type: "Text" },
        gtin13: { type: "Text" },
        gtin12: { type: "Text" },
        gtin14: { type: "Text" },
        material: { type: "Product", foreign: true }, // Beautiful. This is when you know it's working.
        hasMerchantReturnPolicy: { type: "Text" },
        weight: { type: "Text" },
        isSimilarTo: { type: "Product", foreign: true }, // Beautiful. This is when you know it's working.
        pattern: { type: "Text" },
        size: { type: "Text" },
        gtin: { type: "Text" },
        color: { type: "Text" },
        isRelatedTo: { type: "Product", foreign: true }, // Beautiful. This is when you know it's working.
        productID: { type: "Text" }
      },
      name: "Product",
      subs: ["Thing"]
    },
    1: {
      fields: {
        inProductGroupWithID: { type: "Text" },
        model: { type: "ProductModel", foreign: true },
        aggregateRating: { type: "AggregateRating", foreign: true },
        isConsumableFor: { type: "Product", foreign: true },
        hasProductReturnPolicy: { type: "ProductReturnPolicy", foreign: true },
        reviews: { type: "Review", foreign: true },
        offers: { type: "Offer", foreign: true },
        award: { type: "Text" },
        category: { type: "Thing", foreign: true },
        width: { type: "Distance", foreign: true },
        awards: { type: "Text" },
        additionalProperty: { type: "PropertyValue", foreign: true },
        nsn: { type: "Text" },
        manufacturer: { type: "Organization", foreign: true },
        sku: { type: "Text" },
        mpn: { type: "Text" },
        audience: { type: "Text", enums: ["Researcher"] },
        height: { type: "Distance", foreign: true },
        gtin8: { type: "Text" },
        review: { type: "Review", foreign: true },
        depth: { type: "Distance", foreign: true },
        productionDate: { type: "Date" },
        purchaseDate: { type: "Date" },
        itemCondition: {
          type: "Text",
          enums: [
            "DamagedCondition",
            "RefurbishedCondition",
            "UsedCondition",
            "NewCondition"
          ]
        },
        slogan: { type: "Text" },
        brand: { type: "Organization", foreign: true },
        releaseDate: { type: "Date" },
        isAccessoryOrSparePartFor: { type: "Product", foreign: true },
        logo: { type: "ImageObject", foreign: true },
        isVariantOf: { type: "ProductModel", foreign: true },
        gtin13: { type: "Text" },
        gtin12: { type: "Text" },
        gtin14: { type: "Text" },
        material: { type: "Product", foreign: true },
        hasMerchantReturnPolicy: {
          type: "MerchantReturnPolicy",
          foreign: true
        },
        weight: { type: "QuantitativeValue", foreign: true },
        isSimilarTo: { type: "Product", foreign: true },
        pattern: { type: "DefinedTerm", foreign: true },
        size: { type: "QuantitativeValue", foreign: true },
        gtin: { type: "Text" },
        color: { type: "Text" },
        isRelatedTo: { type: "Product", foreign: true },
        productID: { type: "Text" }
      },
      name: "Product",
      subs: ["Thing"]
    }
  },
  Audiobook: {
    0: {
      fields: {
        readBy: { type: "Text" },
        duration: { type: "Text" }
      },
      name: "Audiobook",
      subs: ["Thing", "MediaObject", "CreativeWork", "AudioObject", "Book"]
    },
    1: {
      fields: {
        readBy: { type: "Person", foreign: true },
        duration: { type: "Duration", foreign: true }
      },
      name: "Audiobook",
      subs: ["Thing", "MediaObject", "CreativeWork", "AudioObject", "Book"]
    }
  },
  ArriveAction: {
    0: {
      fields: {},
      name: "ArriveAction",
      subs: ["Thing", "Action", "MoveAction"]
    },
    1: {
      fields: {},
      name: "ArriveAction",
      subs: ["Thing", "Action", "MoveAction"]
    }
  },
  MedicalOrganization: {
    0: {
      fields: {
        healthPlanNetworkId: { type: "Text" },
        medicalSpecialty: {
          type: "Text",
          enums: [
            "PrimaryCare",
            "SpeechPathology",
            "Genetic",
            "Rheumatologic",
            "Anesthesia",
            "Emergency",
            "Gynecologic",
            "Surgical",
            "Dentistry",
            "Nursing",
            "Hematologic",
            "Pulmonary",
            "Neurologic",
            "PharmacySpecialty",
            "PublicHealth",
            "Geriatric",
            "Podiatric",
            "Urologic",
            "Midwifery",
            "Musculoskeletal",
            "Dermatology",
            "DietNutrition",
            "Physiotherapy",
            "RespiratoryTherapy",
            "Psychiatric",
            "CommunityHealth",
            "Cardiovascular",
            "Toxicologic",
            "Gastroenterologic",
            "Oncologic",
            "Renal",
            "Dermatologic",
            "PlasticSurgery",
            "LaboratoryScience",
            "Obstetric",
            "Otolaryngologic",
            "Endocrine",
            "Pathology",
            "Infectious",
            "Optometric",
            "Pediatric",
            "Radiography"
          ]
        },
        isAcceptingNewPatients: { type: "Boolean" }
      },
      name: "MedicalOrganization",
      subs: ["Thing", "Organization"]
    },
    1: {
      fields: {
        healthPlanNetworkId: { type: "Text" },
        medicalSpecialty: {
          type: "Text",
          enums: [
            "PrimaryCare",
            "SpeechPathology",
            "Genetic",
            "Rheumatologic",
            "Anesthesia",
            "Emergency",
            "Gynecologic",
            "Surgical",
            "Dentistry",
            "Nursing",
            "Hematologic",
            "Pulmonary",
            "Neurologic",
            "PharmacySpecialty",
            "PublicHealth",
            "Geriatric",
            "Podiatric",
            "Urologic",
            "Midwifery",
            "Musculoskeletal",
            "Dermatology",
            "DietNutrition",
            "Physiotherapy",
            "RespiratoryTherapy",
            "Psychiatric",
            "CommunityHealth",
            "Cardiovascular",
            "Toxicologic",
            "Gastroenterologic",
            "Oncologic",
            "Renal",
            "Dermatologic",
            "PlasticSurgery",
            "LaboratoryScience",
            "Obstetric",
            "Otolaryngologic",
            "Endocrine",
            "Pathology",
            "Infectious",
            "Optometric",
            "Pediatric",
            "Radiography"
          ]
        },
        isAcceptingNewPatients: { type: "Boolean" }
      },
      name: "MedicalOrganization",
      subs: ["Thing", "Organization"]
    }
  },
  ProductGroup: {
    0: {
      fields: {
        productGroupID: { type: "Text" },
        hasVariant: { type: "Product", foreign: true },
        variesBy: { type: "Text" }
      },
      name: "ProductGroup",
      subs: ["Thing", "Product"]
    },
    1: {
      fields: {
        productGroupID: { type: "Text" },
        hasVariant: { type: "Product", foreign: true },
        variesBy: { type: "DefinedTerm", foreign: true }
      },
      name: "ProductGroup",
      subs: ["Thing", "Product"]
    }
  }
})) {
  describe(`class | ThingBuilder | ${model} modelMaker schemaorg 9.0`, () => {
    for (let [depth, expectModelMade] of Object.entries(tests)) {
      it(`${model} at depth ${depth}`, () => {
        let opts = { depth: depth, comments: false }
        let modelsMined = this.thingBuilder.modelMiner([model], opts)
        let modelMade = this.thingBuilder.modelMaker(model, modelsMined, opts)
        if (debug) {
          if (!this.jay.hasOwnProperty(model)) this.jay[model] = {}
          this.jay[model][depth] = modelMade
        }
        modelMade.should.be.eql(expectModelMade)
      })
    }
  })
}
