import { should } from "chai";
import thingletCreator from "../src/thinglet-creator.js";

should();

describe("thing | -let", () => {
  it("makes a `thing`", async () => {
    let thing = await thingletCreator("Thing");
    thing.should.be.eql({
      additionalType: "",
      alternateName: "",
      description: "",
      disambiguatingDescription: "",
      identifier: "",
      image: "",
      mainEntityOfPage: "Thing",
      name: "",
      potentialAction: "",
      sameAs: "",
      subjectOf: "",
      url: "",
      ItemList: { itemListElement: [], itemListOrder: "", numberOfItems: 0 },
    });
  });
  it("makes a `hotel`", async () => {
    let thing = await thingletCreator("Hotel");
    thing.should.be.eql({
      additionalType: "",
      alternateName: "",
      description: "",
      disambiguatingDescription: "",
      identifier: "",
      image: "",
      mainEntityOfPage: "Thing",
      name: "",
      potentialAction: "",
      sameAs: "",
      subjectOf: "",
      url: "",
      LodgingBusiness: {
        amenityFeature: "",
        audience: "",
        availableLanguage: "",
        checkinTime: "1970-01-01T00:00:00.000Z",
        checkoutTime: "1970-01-01T00:00:00.000Z",
        numberOfRooms: 0,
        petsAllowed: false,
        starRating: "",
      },
      LocalBusiness: {
        branchOf: "",
        currenciesAccepted: "",
        openingHours: "",
        paymentAccepted: "",
        priceRange: "",
      },
      Organization: {
        actionableFeedbackPolicy: "",
        address: "",
        aggregateRating: "",
        alumni: "",
        areaServed: "",
        award: "",
        awards: "",
        brand: "",
        contactPoint: "",
        contactPoints: "",
        correctionsPolicy: "",
        department: "",
        dissolutionDate: "1970-01-01",
        diversityPolicy: "",
        diversityStaffingReport: "",
        duns: "",
        email: "",
        employee: "",
        employees: "",
        ethicsPolicy: "",
        event: "",
        events: "",
        faxNumber: "",
        founder: "",
        founders: "",
        foundingDate: "1970-01-01",
        foundingLocation: "",
        funder: "",
        globalLocationNumber: "",
        hasCredential: "",
        hasMerchantReturnPolicy: "",
        hasOfferCatalog: "",
        hasPOS: "",
        hasProductReturnPolicy: "",
        interactionStatistic: "",
        isicV4: "",
        knowsAbout: "",
        knowsLanguage: "",
        legalName: "",
        leiCode: "",
        location: "",
        logo: "",
        makesOffer: "",
        member: "",
        memberOf: "",
        members: "",
        naics: "",
        nonprofitStatus: "",
        numberOfEmployees: "",
        ownershipFundingInfo: "",
        owns: "",
        parentOrganization: "",
        publishingPrinciples: "",
        review: "",
        reviews: "",
        seeks: "",
        serviceArea: "",
        slogan: "",
        sponsor: "",
        subOrganization: "",
        taxID: "",
        telephone: "",
        unnamedSourcesPolicy: "",
        vatID: "",
      },
      Place: {
        additionalProperty: "",
        address: "",
        aggregateRating: "",
        amenityFeature: "",
        branchCode: "",
        containedIn: "",
        containedInPlace: "",
        containsPlace: "",
        event: "",
        events: "",
        faxNumber: "",
        geo: "",
        geoContains: "",
        geoCoveredBy: "",
        geoCovers: "",
        geoCrosses: "",
        geoDisjoint: "",
        geoEquals: "",
        geoIntersects: "",
        geoOverlaps: "",
        geoTouches: "",
        geoWithin: "",
        globalLocationNumber: "",
        hasDriveThroughService: false,
        hasMap: "",
        isAccessibleForFree: false,
        isicV4: "",
        latitude: 0,
        logo: "",
        longitude: 0,
        map: "",
        maps: "",
        maximumAttendeeCapacity: 0,
        openingHoursSpecification: "",
        photo: "",
        photos: "",
        publicAccess: false,
        review: "",
        reviews: "",
        slogan: "",
        smokingAllowed: false,
        specialOpeningHoursSpecification: "",
        telephone: "",
        tourBookingPage: "",
      },
      Hotel: {},
      ItemList: {
        itemListElement: [],
        itemListOrder: "",
        numberOfItems: 0,
      },
    });
  });
});
