import Action from "../Action.js"
import ChooseAction from "./ChooseAction.js"
import FindAction from "./FindAction.js"
import ImportAction from "./ImportAction.js"
import QuoteAction from "./QuoteAction.js"
import ReadAction from "./ReadAction.js"
import ReceiveAction from "./ReceiveAction.js"
import SearchAction from "./SearchAction.js"
import UpdateAction from "./UpdateAction.js"
import ViewAction from "./ViewAction.js"
import WriteAction from "./WriteAction.js"

export const Actions = new Array(
  "Action",
  "ConsumeAction",
  "OrganizeAction",
  "DiscoverAction",
  "CreateAction",
  "UpdateAction",
  "ReadAction",
  "DeleteAction",
  "ViewAction",
  "InsertAction",
  "RejectAction",
  "AddAction",
  "SearchAction",
  "AuthorizeAction",
  "JoinAction",
  "LeaveAction",
  "ControlAction",
  "EndorseAction",
  "InviteAction",
  "AcceptAction",
  "FindAction",
  "ControlAction",
  "CancelAction",
  "CheckAction",
  "CheckInAction",
  "CheckOutAction",
  "TakeAction",
  "MoveAction",
  "UseAction",
  "ViewAction",
  "WriteAction",
  "AchieveAction",
  "ActivateAction",
  "AgreeAction",
  "AllocateAction",
  "ApplyAction",
  "ArriveAction",
  "AskAction",
  "AssessAction",
  "AssignAction",
  "BefriendAction",
  "BookmarkAction",
  "BorrowAction",
  "BuyAction",
  "ChooseAction",
  "CommentAction",
  "CommunicateAction",
  "CookAction",
  "DeactivateAction",
  "DepartAction",
  "DisagreeAction",
  "DislikeAction",
  "DonateAction",
  "DownloadAction",
  "DrawAction",
  "DrinkAction",
  "EatAction",
  "ExerciseAction",
  "FilmAction",
  "FollowAction",
  "GiveAction",
  "IgnoreAction",
  "InformAction",
  "InstallAction",
  "InteractAction",
  "LendAction",
  "LikeAction",
  "ListenAction",
  "LoseAction",
  "MarryAction",
  "MoneyTransfer",
  "OrderAction",
  "PaintAction",
  "PayAction",
  "PerformAction",
  "PhotographAction",
  "PlanAction",
  "PlayAction",
  "PreOrderAction",
  "QuoteAction",
  "ReactAction",
  "ReceiveAction",
  "RegisterAction",
  "RentAction",
  "ReplaceAction",
  "ReplyAction",
  "ReserveAction",
  "ResumeAction",
  "ReturnAction",
  "ReviewAction",
  "ScheduleAction",
  "SellAction",
  "SendAction",
  "ShareAction",
  "SubscribeAction",
  "SuspendAction",
  "TieAction",
  "TipAction",
  "TrackAction",
  "TradeAction",
  "TransferAction",
  "TravelAction",
  "UnRegisterAction",
  "VoteAction",
  "WantAction",
  "WatchAction",
  "WearAction",
  "WinAction",
).reduce(
  (acc, key) =>
    new Object({
      ...acc,
      // Default action is to return `thing` with its Action completed.
      [key]: {
        mainEntityOfPage: key,
        Action: { target: Action("CompletedActionStatus") },
      },
    }),
  {},
)

export {
  Action,
  ChooseAction,
  FindAction,
  ImportAction,
  QuoteAction,
  ReadAction,
  ReceiveAction,
  SearchAction,
  UpdateAction,
  ViewAction,
  WriteAction,
}

export default {
  ...Actions,
  Action,
  ChooseAction,
  FindAction,
  ImportAction,
  QuoteAction,
  ReadAction,
  ReceiveAction,
  SearchAction,
  UpdateAction,
  ViewAction,
  WriteAction,
}
